name = "SymbolConverters"
uuid = "0b0e1d30-6475-4286-a107-4b7aba88ddd2"
authors = ["Darryl Gamroth <dgamroth@rubus.ca>"]
version = "0.1.0"

[deps]
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"

[compat]
StringViews = "1.3.4"
UnsafeArrays = "1.0.6"
